FROM node:17
ENV REACT_APP_GITHUB_ACTOR=${GITHUB_ACTOR}
ENV REACT_APP_GITHUB_SERVER_URL=${GITHUB_SERVER_URL}
ENV REACT_APP_GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
WORKDIR /code
COPY . /code
RUN npm install &&\
    npm cache clean --force
RUN npm run build
ENTRYPOINT [ "node","/code/action.js"]